name: arsenl-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - curl=8.1.2=h68f0423_0
  - cytoolz=1.1.0=py310h29418f3_1
  - expat=2.7.3=h9214b88_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - glib=2.84.0=h3d4babf_0
  - glib-tools=2.84.0=h4394cf3_0
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.12.2=nompi_h57737ce_101
  - icu=70.1=h0e60522_0
  - jpeg=9e=hcfcfb64_3
  - krb5=1.20.1=heb0366b_0
  - libaec=1.1.4=h20038f6_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libcurl=8.1.2=h68f0423_0
  - libffi=3.4.4=hd77b12b_1
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.84.0=h7025463_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - libnetcdf=4.8.1=nompi_h8c042bf_106
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.50=h7351971_1
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libvorbis=1.3.7=h5112557_2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.5=hfa2b4ca_0
  - mkl=2025.3.0=hac47afa_454
  - netcdf4=1.6.0=nompi_py310h459bb5f_103
  - openssl=3.5.4=h725018a_0
  - pandas=1.4.3=py310hf5e1058_0
  - pcre2=10.44=h99c9b8b_2
  - pip=25.2=pyhc872135_1
  - pyqt=5.15.4=py310hbabf5d4_1
  - pyqt5-sip=12.9.0=py310h8a704f9_1
  - python=3.10.19=h981015d_0
  - python_abi=3.10=2_cp310
  - qt-main=5.15.8=h720456b_6
  - sip=6.5.1=py310h8a704f9_2
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2022.3.0=hd094cb3_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - asttokens==2.0.5
      - attrs==25.1.0
      - backcall==0.2.0
      - backports-functools-lru-cache==1.6.4
      - bokeh==2.4.3
      - bottleneck==1.6.0
      - brotlipy==0.7.0
      - certifi==2022.6.15
      - cffi==2.0.0
      - cfgrib==0.9.15.0
      - cftime==1.6.0
      - charset-normalizer==2.1.0
      - click==8.1.3
      - cloudpickle==2.1.0
      - colorama==0.4.5
      - cryptography==37.0.2
      - cycler==0.11.0
      - dask==2022.6.1
      - debugpy==1.6.0
      - decorator==5.1.1
      - distributed==2022.6.1
      - eccodes==2.40.0
      - entrypoints==0.4
      - executing==0.8.3
      - findlibs==0.1.0
      - flexcache==0.3
      - flexparser==0.4
      - fonttools==4.33.3
      - fsspec==2022.5.0
      - geographiclib==2.0
      - geopy==2.4.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - heapdict==1.0.1
      - idna==3.3
      - imageio==2.34.0
      - importlib-metadata==4.11.4
      - ipykernel==6.15.0
      - ipython==8.4.0
      - jedi==0.18.1
      - jinja2==3.1.2
      - jupyter-client==7.3.4
      - jupyter-core==4.10.0
      - kiwisolver==1.4.3
      - locket==1.0.0
      - lz4==4.0.0
      - markupsafe==2.1.1
      - matplotlib==3.5.2
      - matplotlib-inline==0.1.3
      - metpy==1.6.3
      - msgpack==1.0.4
      - munkres==1.1.4
      - nest-asyncio==1.5.5
      - numexpr==2.14.1
      - numpy==1.24.4
      - opencv-python==4.10.0.84
      - packaging==21.3
      - parso==0.8.3
      - partd==1.2.0
      - pickleshare==0.7.5
      - pillow==11.0.0
      - pint==0.24.4
      - platformdirs==4.3.7
      - pooch==1.8.2
      - prompt-toolkit==3.0.30
      - psutil==5.9.1
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pycparser==2.21
      - pygments==2.12.0
      - pymsis==0.10.0
      - pyopenssl==22.0.0
      - pyparsing==3.0.9
      - pyproj==3.7.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytz==2022.1
      - pywin32==311
      - pyyaml==6.0
      - pyzmq==23.2.0
      - requests==2.32.3
      - scipy==1.8.1
      - seaborn==0.13.2
      - setuptools==75.5.0
      - six==1.16.0
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - stack-data==0.3.0
      - tblib==1.7.0
      - thop==0.1.1-2209072238
      - toolz==0.11.2
      - torch==1.12.0
      - torchaudio==0.12.0
      - torchvision==0.13.0
      - tornado==6.1
      - tqdm==4.67.0
      - traitlets==5.3.0
      - typing-extensions==4.7.1
      - ultralytics==8.3.31
      - ultralytics-thop==2.0.11
      - unicodedata2==14.0.0
      - urllib3==1.26.9
      - wcwidth==0.2.5
      - wheel==0.37.1
      - win-inet-pton==1.1.0
      - xarray==2022.3.0
      - zict==2.2.0
      - zipp==3.8.0
prefix: C:\Users\grant\anaconda3\envs\arsenl-conda
